### ISSUE TITLE
Remove dependency on Docker Compose

### ISSUE THREAD

**Issue by vyshane** [vyshane/docker-compose-kubernetes#12]
We should keep external dependencies to a minimum. Kubernetes addons like DNS and kube-ui are launched using Kubernetes itself, and `docker run` is sufficient for bringing up the base Kubernetes system.

**Comment by arnaud-deprez** [comment]
Agree to run kubernetes addons in kubernetes itself but we should keep using docker-compose for etcd kube-master and kube-proxy as it's easier to maintain and it's a standard docker tool.
