### ISSUE TITLE
nslookup working only for fully qualified domain names

### ISSUE THREAD

**Issue by leonfs** [vyshane/docker-compose-kubernetes#14]
When following Kubernetes documentation (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns) on how to test the DNS resolution:

```
kubectl exec busybox -- nslookup kubernetes.default
```

The resolution fails. But if we change kubernetes.default to the fully qualified name:

```
kubectl exec busybox -- nslookup kubernetes.default.svc.cluster.local
```

The resolution succeeds.

**Comment by vyshane** [comment]
With DNS on, I can resolve `kubernetes`, `kubernetes.default` and `kubernetes.default.svc.cluster.local`. With DNS turned off for the cluster, I can't resolve any of them.

I'm not sure why `kubernetes.default` wouldn't work for you while `kubernetes.default.svc.cluster.local` does.
