### ISSUE TITLE
Stuck at waiting for cluster

### ISSUE THREAD

**Issue by bkuhl** [vyshane/docker-compose-kubernetes#2]
Running `./kube-up-docker-machine.sh` sets up the VM and such, but gets stuck at `Waiting for Kubernetes cluster to become available...`

```
$ ./kube-up-docker-machine.sh
kubernetes_skydns_1 is up-to-date
kubernetes_master_1 is up-to-date
kubernetes_kube2sky_1 is up-to-date
kubernetes_etcd_1 is up-to-date
kubernetes_proxy_1 is up-to-date
Waiting for Kubernetes cluster to become available...
```

Looks like the underlying cause may be that `kubectl` isn't found on my mac.  Should that command be available at this step?

**Comment by vyshane** [comment]
Ah, yes, you'll need `kubectl`. Easiest way to install it on OS X is via Homebrew:

``` sh
brew install kubernetes-cli
```

**Comment by vyshane** [comment]
The kube-up.sh script will now check whether the commands it depends on are available. It exits with a message if requirements are not met: 0189903d3f7f2611bfe0ab1a5b39d4ebf76797cf

I've also merged the two kube-up scripts into a single one that works for both local Docker Engine and Docker Engine via Docker Machine.

**Comment by lgomez** [comment]
Hello,

I'm experiencing a similar problem but I do have kubectl installed. ./kube-up.sh hangs at:

```
...
Creating kubernetes_etcd_1
Creating kubernetes_proxy_1
Waiting for Kubernetes cluster to become available...
```

If I run `kubectl version` on another shell I get

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
error: couldn't read version from server: Get https://104.197.252.197/api: dial tcp 104.197.252.197:443: i/o timeout
```

Any ideas?

Thank you very much for your help.

**Comment by vyshane** [comment]
Looks like your kubectl is configured to talk to another cluster at 104.197.252.197.

**Comment by lgomez** [comment]
You are absolutely right. I ws not aware of the multiple configurations, contexts, etc. I get it now. Thank you!
