### ISSUE TITLE
$DOCKER_HOST not defined on linux

### ISSUE THREAD

**Issue by henridwyer** [vyshane/docker-compose-kubernetes#5]
This makes the 
dns_host=$(echo $DOCKER_HOST | awk -F'[/:]' '{print $4}')
in activate-dns.sh an empty string, ultimately leading to the error:
The Endpoints "kube-dns" is invalid:subsets[0].addresses[0].ip: invalid value '': invalid IPv4 address

In that case, should it be replaced by 127.0.0.1 ? (that's what fixed it for me)

**Comment by vyshane** [comment]
Thanks for the heads up. I've just fixed this in 4cf6a773172c55aa8aabbbdf50db636ed98a2c25.
