### ISSUE TITLE
subsets[0].addresses[0].ip: invalid value '127.0.0.1', Details: may not be in the loopback range (127.0.0.0/8)

### ISSUE THREAD

**Issue by dragonde** [vyshane/docker-compose-kubernetes#6]
I run docker-composer-kubernetes on Linux without $DOCKER_HOST assigned, so it set DNS ENDPOIT to 127.0.0.1. However, in kubernetes the loopback IP can not be used as Endpoint IP(*), so I get error:

subsets[0].addresses[0].ip: invalid value '127.0.0.1', Details: may not be in the loopback range (127.0.0.0/8)

*)  https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md

**Comment by vyshane** [comment]
Bummer. That was a "fix" for #5. I'm open to suggestions on how to handle this on Linux.

**Comment by metral** [comment]
+1 on hitting this issue also with skydns setup in Ubuntu 14.04 VM

Are there any resolutions?

**Comment by ReSearchITEng** [comment]
+1 on hitting this issue also when trying to force nginx controller listen on loopback.
```
helm install --set controller.service.externalIPs[0]=127.0.0.1 --name nginx-ingress --namespace kube-system stable/nginx-ingress --set rbac.create=true --set controller.stats.enabled=true --set controller.service.type=NodePort --set controller.service.nodePorts.http=32080 --set controller.service.nodePorts.https=32443 --set controller.stats.enabled=true 
Error: release nginx-ingress failed: Service "nginx-ingress-nginx-ingress-controller" is invalid: spec.externalIPs[0]: Invalid value: "127.0.0.1": may not be in the loopback range (127.0.0.0/8)
```
