### ISSUE TITLE
docker & docker-machine get slow to respond with timeout

### ISSUE THREAD

**Issue by arnaud-deprez** [vyshane/docker-compose-kubernetes#8]
Hi,

On MAC OSX (with boot2docker), my docker and docker-machine are getting slow when my kubernetes cluster is up, after a while I get some timeout and then it doesn't work at all while kubectl still works fine.
Did you note this or is it just me ? Maybe you don't have this issue if you are using linux.

Please share your experience.

Arnaud.

**Comment by vyshane** [comment]
I haven't noticed any slowdowns. Does the boot2docker VM go back to normal after you do a kube-down?

**Comment by arnaud-deprez** [comment]
It depends. Sometimes, I had to restart my machine. I've solved part of the problem by using "pid: host" option in the docker-compose file for the master. But I'm still testing it before bring you a new PR.

**Comment by leonfs** [comment]
I've been experiencing the same issue. Once the Kubernetes cluster is up and running, after a few minutes, the docker machine becomes completely unresponsive.

**Comment by vyshane** [comment]
I assume that you have allocated enough resources to your Docker machine VM for both Kubernetes and the workload that you are running?

**Comment by leonfs** [comment]
Yes, I do have enough resources. Running the VM with 2 GB. When executing free on the VM I still have 1.2 GB RAM and 1.4 GB SWAP. 

I managed to corner the problem. If I don't access/load Kube UI then everything works fine. Everything keeps responsive.

**Comment by arnaud-deprez** [comment]
Hi,

I still have the same problem too. I'll try to see if I have the same behavior than you leonf.

But on my side, the docker machine itself isn't really unresponsive, I can still run kubectl, load kube-ui, etc. But when I run docker-machine to switch to another machine, or even the docker command on the same machine, then it gets slow or blocked.
So on my side, it seems related to docker commands. I saw a post from @jpetazo https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ where it can eventually explain the problem. The problem is mounting the docker.sock in kubernetes isn't sufficient anymore, it cause some other issues. It's because kubernetes expects to have a solid installation of docker and not only the client part.

Is it the same on your side ?

**Comment by arnaud-deprez** [comment]
I confirm, without accessing to kube-ui, if I use another terminal and try this command : 

``` sh
~ eval "$(docker-machine env k8s)"
Error running connection boilerplate: Error getting driver URL: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :
```

But sometimes, it works.

**Comment by leonfs** [comment]
The problem is not Docker nor Kubernetes but the Port forwarding technique. I haven't figured it out yet if it's an issue in docker-machine. But if you run 

```
ssh -L 8080:localhost:8080 -i ~/.docker/machine/machines/default/id_rsa docker@$(docker-machine ip default)
```

It will start working perfectly, no delays.

**Comment by arnaud-deprez** [comment]
Yeah I've noticed that too. But docker client doesn't use port forwarding. So it seems that the configuration of docker-machine doesn't work well. The thing is, I've not yet noticed something special there.

**Comment by leonfs** [comment]
What version of docker-machine are you using? I'm on 0.5.0 (04cfa58)

**Comment by arnaud-deprez** [comment]
Same version that I've installed using Homebrew: 

``` sh
brew cask install dockertoolbox
```

**Comment by leonfs** [comment]
With the latest version of docker-machine (0.5.5) and docker (1.9.1, build a34a1d5) the issue is gone.

**Comment by arnaud-deprez** [comment]
Good news, it seems to work with me too. Thanks I didn't notice a new version were out. 
I close it.
